services:
  frontend:
    build: ./frontend
    ports:
      - "8000:80"

  api:
    build: ./api
    ports:
      - "8001:8001"
    env_file:
      - .env
    volumes:
      - ./api:/app
      - scanner_bin:/usr/local/bin/shared
    depends_on:
      - db

  db:
    build: ./mysql
    environment:
      MYSQL_DATABASE: ankyloscan
      MYSQL_ROOT_PASSWORD: ${ADMIN_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

  scanner:
    build: ./scanner
    depends_on:
      - db
    environment:
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    volumes:
      - scanner_bin:/usr/local/bin/

welcome:
    image: alpine
    container_name: ankyloscan_setup
    tty: true
    stdin_open: true
    volumes:
      - .:/app
    working_dir: /app
    command: >
      sh -c "
      echo '--------------------------------------------' &&
      echo 'ü¶ñ Configuration AnkyloScan üõ°Ô∏è' &&
      echo '--------------------------------------------' &&
      
      # Question 1 : Gmail üìß
      printf 'Activer Gmail ? (0/1) : ' && read GMAIL_ENABLED < /dev/tty;
      echo \"GMAIL_ENABLED=\$$GMAIL_ENABLED\" >> .env;

      if [ \"\$$GMAIL_ENABLED\" = \"1\" ]; then
          # Question 2 : Email
          printf 'Email Gmail : ' && read GMAIL_USER < /dev/tty;
          echo \"GMAIL_USER=\$$GMAIL_USER\" >> .env;
          
          # Question 3 : AppKey
          printf 'AppKey (16 caract√®res) : ' && read GMAIL_KEY < /dev/tty;
          echo \"GMAIL_APP_KEY=\$$GMAIL_KEY\" >> .env;
      fi &&

      echo '--------------------------------------------' &&
      echo 'Configuration termin√©e ! ‚ú®' &&
      echo 'Tigrounet enregistre tout dans le .env üê±' &&
      echo '--------------------------------------------'"

volumes:
  db_data:
  scanner_bin:
