services:
  frontend:
    build: ./frontend
    ports:
      - "8000:80"

  api: # Alignement corrigÃ© ici ğŸ‘
    build: ./api
    ports:
      - "8001:8001"
    env_file:
      - .env
    volumes:
      - ./api:/app
    depends_on:
      - db

  db:
    build: ./mysql
    environment:
      MYSQL_DATABASE: ankyloscan
      MYSQL_ROOT_PASSWORD: ${ADMIN_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

  scanner:
    build: ./scanner
    depends_on:
      - db
    environment:
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}

  welcome:
    image: alpine
    depends_on:
      - frontend
    command: >
      sh -c "
      echo '--------------------------------------------' &&
      echo 'ğŸ¦– AnkyloScan est prÃªt ! ğŸ›¡ï¸' &&
      echo 'Lien : http://localhost:8000' &&
      echo 'User Admin : admin' &&
      echo 'MDP Admin : ${ADMIN_PASSWORD:-password_aleatoire}' &&
      echo 'Tigrounet veille sur tes donnÃ©es ! ğŸ±ğŸ˜¶' &&
      echo '--------------------------------------------'"

volumes:
  db_data:
