services:
  frontend:
    build: ./frontend
    ports:
      - "8000:80"

  api:
    build: ./api
    ports:
      - "8001:8001"
    volumes:
      - ./api:/app

  db:
    build: ./mysql
    ports:
      - "8002:3306"
    environment:
      MYSQL_DATABASE: ankyloscan
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - db_data:/var/lib/mysql

  # âœ¨ Ce bloc affiche tes messages dans le terminal
  welcome:
    image: alpine
    depends_on:
      - frontend
    command: >
      sh -c "echo '--------------------------------------------' &&
             echo 'ğŸ¦– AnkyloScan est prÃªt ! ğŸ›¡ï¸' &&
             echo 'Lien : http://localhost:8000' &&
             echo 'Tigrounet veille sur tes donnÃ©es ! ğŸ±ğŸ˜¶' &&
             echo '--------------------------------------------'"

volumes:
  db_data:
